services:
  - type: web
    name: inventory-management-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    staticPublishPath: app/static
    plan: free
    autoDeploy: true
    pythonVersion: 3.10

    # Optional: If you want to expose .env variables
    envFile: app/.env
